### ISSUE TITLE
Support for netstandard1.3

### ISSUE THREAD

**Issue by fubar-coder** [DecaTec/Portable-WebDAV-Library#16]
It would be nice when your project would support netstandard1.3. You can reuse the source for the .NET Framework without changes (tried with master). TBH: It might be useful to wait for the VS 2017 release (.NET Core 2.0) to ease the pain with the current inconsistencies of the .NET Core tooling.

**Comment by StefH** [comment]
See also (closed pr) ; https://github.com/DecaTec/Portable-WebDAV-Library/pull/7

**Comment by DecaTec** [comment]
As you can see in #7, I decided to stick with the old project structure a few months ago.
Honestly, I have to collect a few more information about .NET Core, its tooling and the advantages compared to the current project structure.

Do you have a particular case were you'll need support of netstandard1.3?

**Comment by fubar-coder** [comment]
I need it for testing my WebDAV server from a netcoreapp. Currently, I use a copy of the WebDAV client source code, but I'd prefer the "real thing" :grin:

**Comment by StefH** [comment]
Hi Mark.

For testing purposes, you can also use this client https://www.nuget.org/packages/WebDAV-Client which supports netstandard 1.1 and up.

**Comment by DecaTec** [comment]
I'll try to convert the NetFx part to .NET Core. There shouldn't be any drawbacks.

But I think I have to keep up the seperation of NetFx (NetCore then) and UWP as Windows.Web.Http.HttpClient is not available in .NET Core unfortunately.

**Comment by fubar-coder** [comment]
You can use the NuGet package `System.Net.Http` in a UWP app as it supports netcore50 and netstandard1.3, and according to [this netstandard versions document](https://github.com/dotnet/standard/blob/master/docs/versions.md), UWP supports the netstandard up to 1.4.

You can see the netcore50 support in [this repository directory](https://github.com/dotnet/corefx/tree/master/src/System.Net.Http/src/netcore50/System/Net). It doesn't use `Windows.Web.Http.HttpClient`, but it does use `Windows.Web.Http.Filters.HttpBaseProtocolFilter` for its requests.

EDIT: Just one thing: Please don't reference NETStandard.Library when targeting the full .NET Framework, because all its dependencies may cause some trouble for the users of your package. Use the real framework assemblies for the .NET Framework instead.

**Comment by DecaTec** [comment]
Yes, I could use `System.Net.Http.HttpClient` in UWP projects. Hopefully, the bug I've ran into a while ago is fixed (see https://github.com/DecaTec/Portable-WebDAV-Library/wiki/Portable-WebDAV-Library-in-UWP-projects).
The main reason why I decided to use `Windows.Web.Http.HttpClient` is the easy way to allow put/post with a progress (`IProgress<HttpProgress>`). That part is missing on `System.Net.Http.HttpClient`.

> EDIT: Just one thing: Please don't reference NETStandard.Library when targeting the full .NET Framework, because all its dependencies may cause some trouble for the users of your package. Use the real framework assemblies for the .NET Framework instead.

Can you elaborate this a bit more?

**Comment by fubar-coder** [comment]
The problem I encountered is, that using multiple netstandard packages referencing the same dependencies but with different package versions are causing many binding redirects (in desktop projects) which are notoriously hard to maintain. Using the framework assemblies "fixes" this problem, because it just references the target framework assembly.

But in your case, it should be fine to use `System.Net.Http` 4.3.0, because its dependencies are sane for desktop projects.

**Comment by DecaTec** [comment]
OK, so here's my plan:

- I'll wait until VS2017 is released. Then there's no need of installing additional tools for .NET Core. Hopefully the tools are out of beta then.
- Meanwhile I'll test with VS2015 on how to convert the NetFx part to .NET Core
- Maybe I'll find a way to enable upload/download with progress using `System.Net.Http.HttpClient`. If that's the case, I could put both parts of the library together which would be the optimal solution (currently I'm not happy with the separation NetFx/UWP)

When It's ok for you, then you could try Stef's WebDAV lib for testing purposes.

**Comment by DecaTec** [comment]
So, after VS 2017 was released, I've prepared to porting the whole library to .NETStabdard 1.1.
You can see a work in progress here: https://github.com/DecaTec/Portable-WebDAV-Library/tree/netstandard

What is missing right now is the documentation, because the SHFB doesn't support netstandard at the moment (see here: https://github.com/EWSoftware/SHFB/issues/255).

However, I was able to support an upload/download with progress, so this is available for all .NetStandard platforms.

As soon as the documentation project can be built against .NETStandard, I'll prepare for the next release. This will be one library for all target platforms (and no separation between NetFx and UWP).  It'll be great if you could have a look at the new branch and test it against your WebDAV implementations.

**Comment by fubar-coder** [comment]
I have the same problem regarding the documentation. I use docfx which cannot handle those new .NET Core csproj files too. My workaround is, that I create a .NET Framework project and use this for the documentation creation.

Can you please create a [MyGet](https://www.myget.org/) feed? This would allow simple usage in other projects.

Thank you for your work!

**Comment by DecaTec** [comment]
You can find the MyGet feed [here](https://www.myget.org/feed/decatec/package/nuget/PortableWebDavLibrary).

Edit:

> I have the same problem regarding the documentation. I use docfx which cannot handle those new .NET Core csproj files too. My workaround is, that I create a .NET Framework project and use this for the documentation creation.

Unfortunately, this doesn't seem to work with SHFB. It's only pulling the 'dummy' project for documentation purposes.

**Comment by DecaTec** [comment]
Well, finally managed to create the doc by adding a dummy project and linking all the files in.
It works, but that's definitely not the perfect solution...

**Comment by fubar-coder** [comment]
Can you please change the version number to 0.7.0-beta01 or something like that? Otherwise NuGet isn't able to distinguish between 0.6.3 from nuget.org and myget.org.

**Comment by fubar-coder** [comment]
The NuGet package doesn't contain a netstandard library - only net and profile32.

**Comment by DecaTec** [comment]
It's not released on NuGet yet, it's just the branch.

**Comment by fubar-coder** [comment]
I meant the *.nupkg file you published on myget.

**Comment by DecaTec** [comment]
OK, I think I have to get used to MyGet first. When I get it right, I can publish packages on MyGet without releasing them on NuGet (e.g. for preview purposes). I will take care of this in the following days.

**Comment by DecaTec** [comment]
So, this should do the trick: https://www.myget.org/feed/decatec/package/nuget/PortableWebDavLibrary

**Comment by fubar-coder** [comment]
Nice that you support netstandard1.1. The library version 0.7.0 works for me.

**Comment by DecaTec** [comment]
Thanks for your feedback!

I've created a new feed extra for previews. These Packages are also marked as beta versions (not to get confused with the upcoming release): https://www.myget.org/feed/decatec-preview/package/nuget/PortableWebDavLibrary

**Comment by DecaTec** [comment]
Merged the netstandard brach into main branch.
For greater compatibility, the target ist .NETStandard 1.1, so the library know supports all platforms from .NET Framework 4.5 and later.
