### ISSUE TITLE
Issues when using library in UWP project

### ISSUE THREAD

**Issue by DecaTec** [DecaTec/Portable-WebDAV-Library#2]
**Problem:**
When using the Portable WebDAV Library in a Universal Windows Platform (UWP) project, an exception is thrown when accessing WebDAV resources using _WebDavClient_ or _WebDavSession_ with user credentials:

> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.NotSupportedException: This IRandomAccessStream does not support the GetInputStreamAt method because it requires cloning and this stream does not support cloning.

**Cause of the exception**
The class _WebDavClient_ derives from _System.Net.Http.HttpClient_ in order so send requests to WebDAV resources. The assembly referenced in UWP projects is 

> System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

This version contains a bug in the HttpClient (see [MSDN forums](https://social.msdn.microsoft.com/Forums/vstudio/en-US/ff66088c-6705-40c0-b839-491b6ed6eb76/uwpwindows-10-bug-in-httpclienthttpwebrequest-when-using-network-credentials?forum=wpdevelop)).
This bug will be fixed in a future release of the System.Net.Http assembly.

**Workaround**
To be able to use the Portable WebDAV Library in UWP project, a pre-release version of _System.Net.Http_ has to be used as a workaround.
To use the pre-release version, follow these steps:
- Right click on your project in Visual Studio 
- _Manage NuGet Packages..._
  ![managenugetpackages](https://cloud.githubusercontent.com/assets/9428899/14184677/9ec47a0e-f776-11e5-9caa-4c306d088d6a.png)
- Browse
- Search for 'System.Net.Http' and tick the option _Include prerelease_
- Install the latest beta version of this package
  ![addsystemnethttpprerelease](https://cloud.githubusercontent.com/assets/9428899/14184678/9ec48878-f776-11e5-9374-a4c89cef5f98.png)

**Keep in mind that when using a pre-release package, there might be other bugs or side effects.**

As soon as the System.Net.Http assembly got updated, this workaround will not longer be necessary.

See this [wiki article](https://github.com/DecaTec/Portable-WebDAV-Library/wiki/Portable-WebDAV-Library-in-UWP-projects) for more information.

**Comment by DecaTec** [comment]
Due to other problems when using the Portable WebDAV Library in UWP apps, the library needs to get spit up in two different parts: see https://github.com/DecaTec/Portable-WebDAV-Library/issues/3
With the split (and using Windows.Web.Http.HttpClient in the UWP part of the library), this issue should be solved and the workaround not longer be needed).

**Comment by DecaTec** [comment]
With v0.3.0.0 the Portable WebDAV Library was split into two parts, resolving this issue.
There is no need to add a reference to a prerelease version of System.Net.Http assembly.

Use the DecaTec.WebDav.Uwp.dll in Windows 8.1/Windows Phone 8.1/UWP projects instead.
See [v0.3.0.0 release](https://github.com/DecaTec/Portable-WebDAV-Library/releases/tag/v0.3.0.0).

**Comment by StefH** [comment]
Do you have a specific UWP unit-test which can reproduce this problem ?

**Comment by DecaTec** [comment]
No, but it's probably a good idea to introduce such a test, just to see when System.Net.Http gets updated.
