### ISSUE TITLE
Cannot pass relative URL to methods taking a URL as string

### ISSUE THREAD

**Issue by fubar-coder** [DecaTec/Portable-WebDAV-Library#24]
To allow relative URLs, the conversion from string to `Uri` should be done using `new Uri(requestUrl, UriKind.RelativeOrAbsolute)`.

**Comment by DecaTec** [comment]
Workaround for now would be to use the overloads with an Uri and converting the URL string on the client side.
But good point, this needs to be improved.

**Comment by DecaTec** [comment]
Fixed with https://github.com/DecaTec/Portable-WebDAV-Library/commit/8b5a33619a65e42374d929df333e5a8423cd2e3b
