### ISSUE TITLE
Nuspec issues

### ISSUE THREAD

**Issue by fubar-coder** [DecaTec/Portable-WebDAV-Library#27]
I see the following issues with the current NuGet package:

1. The assemblies for .NET profile 32 (Uwp) and .NET profile 111 (Netfx) have different assembly names.
2. According to [this documentation](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks), the usage of the profile number is not a recommended practice. The TFM for profile 32 should therefore be `portable-win81+wpa81`
3. The profile 111 assembly should be in the lib folder `portable-net45+win8+wpa81`.

NuGet believes - due to the NetFx assembly being in the lib folder - that this is an assembly for the full .NET Framework (version 1,1) is, which doesn't seem right.

**Comment by DecaTec** [comment]
Yes, that's maybe not the best solution. Maybe I'll fix it in a future release. For now it seems to work well.

But the quoted article also says:

> PCLs are not recommended
Although PCLs are supported, package authors should support netstandard instead. The .NET Platform Standard is an evolution of PCLs and represents binary portability across platforms using a single moniker that isn't tied to a static like like portable-a+b+c monikers.

Imho that's the right way to go and should be the next goal for the library.
I only have to find a way to implement upload/download with progress (the UWP style).

**Comment by fubar-coder** [comment]
I'd just keep the UWP PCL.

**Comment by DecaTec** [comment]
Merged the netstandard brach into main branch.
