### ISSUE TITLE
Static Prop.Create* methods don't support lockdiscovery

### ISSUE THREAD

**Issue by fubar-coder** [DecaTec/Portable-WebDAV-Library#28]
The `Prop` class contains (at least one) property (`LockDiscovery`) than is not initializable using the `CreatePropWithEmptyProperties` or `CreatePropWithEmptyPropertiesAll` method.

**Comment by DecaTec** [comment]
Good catch, I forgot about this when I merged the lockdiscovery-PR.
Fixed with https://github.com/DecaTec/Portable-WebDAV-Library/commit/e03287b3b8c4975770742b2e71db13e3e570773d
