### ISSUE TITLE
Support for xml:lang

### ISSUE THREAD

**Issue by fubar-coder** [DecaTec/Portable-WebDAV-Library#29]
According to the [RFC, section 4.3](http://www.webdav.org/specs/rfc4918.html#rfc.section.4.3), the `xml:lang` attribute is allowed for the `prop` element.

**Comment by DecaTec** [comment]
Fixed with https://github.com/DecaTec/Portable-WebDAV-Library/commit/8b71b544a4f8d77da6022d01c445f4e92d5afc60

**Comment by DecaTec** [comment]
Btw this feature is already part of beta2 on [MyGet](https://www.myget.org/feed/decatec-preview/package/nuget/PortableWebDavLibrary/0.7.0-beta2).
