### ISSUE TITLE
Thanks for release 0.7.0

### ISSUE THREAD

**Issue by kant2002** [DecaTec/Portable-WebDAV-Library#33]
I want to say thank you for finally releasing .NET Core version of library.
I was using it before and have to manually provide .NET Core support until you finally remove this burden from me. 
Big Thank You!!!! 🥇

**Comment by DecaTec** [comment]
You're welcome!
Great to see that it was worth the effort.

May I ask for which project(s) you are using the library?

I'll close the "issue" because it's no real issue actually. :smile:

**Comment by kant2002** [comment]
@DecaTec I access SpinetiX video signage which have WebDAV support for uploading content to it. I automate installation of updates on the displays which managed by SpinetiX. These system operate in closed environment with flacky network connection. My application running Windows, but I use .NET Core project to be able support having my app run on Linux if needed.

We operate about 16 SpiinetiX devices such way.
