### ISSUE TITLE
Is there a NuGet Package available

### ISSUE THREAD

**Issue by squadwuschel** [DecaTec/Portable-WebDAV-Library#4]
Hi,

do you habe a NuGet Package for your Solution, sounds great so far and works fine with Owncloud for me.

thx squadwuschel

**Comment by DecaTec** [comment]
Hi,

there isn't a NuGet package yet, but that's on my ToDo list.

**Comment by StefH** [comment]
NuGet can be created easily with https://github.com/DecaTec/Portable-WebDAV-Library/issues/5

**Comment by DecaTec** [comment]
NuGet package available now: https://www.nuget.org/packages/PortableWebDavLibrary

**Comment by StefH** [comment]
Thanks.
