### ISSUE TITLE
Editing WebDavSessionListItem Properties 

### ISSUE THREAD

**Issue by Tronald** [DecaTec/Portable-WebDAV-Library#41]
Is it possible to change and save a WebDavSessionListItem property value of a file on a WebDav server? If it is possible, can it be included in the documentation? If it is not possible, should the WebDavSessionListItem properties be read only?

Example:

```C#
var items = await webDavSession.ListAsync("uri");
var item = items["index"];
item.DisplayName = "New Value";
//Save item                
```

**Comment by DecaTec** [comment]
No, that's not possible.
It's not the way WebDAV works. All the communication between server and client is stateless.

If you want to alter a property of a WebDAV element (e.g. DisplayName), you'll have to use a PROPFIND command with the `WebDavClient` class.

**Comment by Tronald** [comment]
I understand communication is stateless, but the `WebDavSessionListItem` object is mutable. This led me to believe that `WebDavSession` was capable of handling property value changes somehow. 

The ability to alter a property of a WebDAV element, might be a nice addition to the` WebDavSession `methods in the future. If this is not doable, it may be a good idea to make `WebDavSessionListItem` immutable.

I have very little knowledge of WebDAV so this library has been fantastic BTW. I will check out the WebDavClient with PROPFIND.

Thanks for the clarification.

**Comment by DecaTec** [comment]
Oh, sorry, I didn't mean PROPFIND, I meant PROPPATCH.
But maybe it's a good idea to make the WebDavSessionListItem's properties readonly. There's no real need to alter these properties by the client.

And speaking of, WebDavSession has no "high level" possibility for a PROPPATCH. This should be added in the future.

Thanks for the input!

**Comment by DecaTec** [comment]
I've implemented the function to edit `WebDavSessionItem`'s properties and update them on the server using `WebDavSession` (methods `UpdateItemAsync` and `UpdateItemsAsync`).

You can check out a preview of the next version of the lib on [MyGet](https://www.myget.org/feed/decatec-preview/package/nuget/PortableWebDavLibrary).

Keep in mind that many WebDAV servers do not support editing WebDAV properties which may be editable (according to RFC 4918).
