### ISSUE TITLE
Update the system.* dependencies to fix security issue

### ISSUE THREAD

**Issue by TomGroeneboer** [DecaTec/Portable-WebDAV-Library#47]
Please update the System.* dependencies to their new versions. Microsoft has released a security advisory to do so. Please find more info at https://github.com/dotnet/announcements/issues/12

**Comment by DecaTec** [comment]
Resolved with https://github.com/DecaTec/Portable-WebDAV-Library/commit/b6d825d96c056814a6bc595d721603b9a416894d

NuGet package v0.9.1.0 on its way...
