### ISSUE TITLE
Maybe an idea to switch to the new project.json structure?

### ISSUE THREAD

**Issue by StefH** [DecaTec/Portable-WebDAV-Library#5]
When creating a project based on the new project.json structure, you can easily target multiple frameworks in 1 project, for portable you can choose from:
http://embed.plnkr.co/03ck2dCtnJogBKHJ9EjY

Also a NuGet can be created easily.

If you need help, I can offer some help in converting the project.

**Comment by DecaTec** [comment]
Do you have any example for rebuilding the project based on project.json?

If I got it right, targeting multiple frameworks in only one project needs conditional compilation (#IF NET40...) or conditional including files in the csproj. The split into two separate projects and using a shared project is maybe just a temporary solution. At the moment, I'm quite happy with it.

Next on the todo list is creating a Nuget package. At the moment I'm not sure how to create only one Nuget package containing two DLLs which are included depending on the target framework of the project using the Nuget package. Can this be accomplished more easlily with a project.json approach?

**Comment by StefH** [comment]
In one project.json file, you can define multiple frameworks like net45, ... and uap. This will indeed create 1 NuGet with multiple dll's for each framework.

Do you know the full list you want to support?

And probably we need some #IF #ELSE #ENDIF in the source-code files.

I'll will do some investigation and maybe create a pull-request with the changes.

**Comment by DecaTec** [comment]
Honestly, I want to avoid #IF #ELSE #ENDIF, but these will be needed because some code files differ in large parts (and for the clarity of the code).
What are the advantages of using project.json here? I pretty sure that a single Nuget package targeting multiple frameworks can also be done with the current project structure.

**Comment by StefH** [comment]
See https://github.com/DecaTec/Portable-WebDAV-Library/pull/6

**Comment by StefH** [comment]
See pull request : https://github.com/DecaTec/Portable-WebDAV-Library/pull/7

No #IF #ELSE #ENDIF needed.

No problems in using this NuGet in a 4.5.2 project

**Comment by DecaTec** [comment]
See pull request #7 
I'll consider a new project structure for future development.
