### ISSUE TITLE
Disable Expect: 100-continue header?

### ISSUE THREAD

**Issue by devatwork** [DecaTec/Portable-WebDAV-Library#50]
I've an remote server (BaseX in this case) which does not send a response when an `Expect: 100-continue` header is sent along with the request. As far as I can tell the header is automatically appended by .NET Core/libcurl in certain scenarios. I've tested the behavior of WinSCP to see what it does and it does not send the `Expect` header.

Disabling it is pretty straightforward: just set `System.Net.Http.HttpClient.DefaultRequestHeaders.ExpectContinue` to `false`. This can be achieved without an modification to this library.

Did anyone encounter this issue before? If it is valuable I can send a PR if we want to disable the Expect header by default.

**Comment by DecaTec** [comment]
Disabling this header shouldn't be a problem. But what about side effects?
Maybe we can configure this by property of WebDavClient/WebDavSession.

**Comment by devatwork** [comment]
See https://www.w3.org/Protocols/rfc2616/rfc2616-sec8.html section 8.2.3 Use of the 100 (Continue) Status. 

> The purpose of the 100 (Continue) status (see section 10.1.1) is to allow a client that is sending a request message with a request body to determine if the origin server is willing to accept the request (based on the request headers) before the client sends the request body. In some cases, it might either be inappropriate or highly inefficient for the client to send the body if the server will reject the message without looking at the body.

A use case I can think of is creating or updating a large file as describes in this SO post as well: https://stackoverflow.com/questions/33494609/httpclient-defaultrequestheaders-expectcontinue-what-purpose-does-expectcontinu. In all other cases it is an unnecessary round trip.

The question is if we want to still allow the header for uploading requests? In all other cases the request body shouldn't be large in the first place.

Controlling it on `WebDavClient` is easy since it inherits from `HttpClient`. For `WebDavSession` we could it expose it as an property similar to how `WebDavSession.Timeout` works so it can be controlled by the consumer.

Any thoughts on enabling/disabling it by default? Although I need to sleep on this, my first thought would be to disable it by default since it saves overhead in most, if not all, requests and the case where a request payload is too large should not happen that often.

**Comment by DecaTec** [comment]
In your second link it states:

> Think that you are going to upload a 1 GB file to a specific folder on a server. If you start the transfer directly and the server does not accept files bigger than 512 MB or the folder does not exist, the server will not accept the file, and the transfer will be a waste of resources for both sides.

Because of this I won't disable it by default. I think a separate property should be the best solution here.

**Comment by devatwork** [comment]
Fair enough. Do you want me to send a PR to add the property to `WebDavSession`? One can already set the property on `WebDavClient` directly.

**Comment by DecaTec** [comment]
If you have the PR ready, send it.
Otherwise I'll do this tomorrow.

**Comment by DecaTec** [comment]
Well, after I had already implemented it, it came to my mind that this is one specific header which gets exposed for `WebDavSession`. This may solve this issue, but there will also be other headers which someone may want to set for `WebDavSession`.

So, my solution is now to expose the `DefaultRequestHeaders` of the underlying `WebDavClient` in `WebDavSession`. This way, any header can be set with no changes needed in the WebDAV lib. See https://github.com/DecaTec/Portable-WebDAV-Library/commit/e9b842ac065d1b4d0267bc837091ffcac4b16489

@devatwork For testing purposes I created a MyGet package with these changes included here: https://www.myget.org/feed/decatec-preview/package/nuget/PortableWebDavLibrary
When this solution works for you (I also added some unit tests regarding the Expect header), this should be part of the upcoming v1.1.0.0 (I'm planning the release on Friday).

**Comment by devatwork** [comment]
Sorry for getting back this late, I got swamped today.

The changes look good to me. We're currently only using `WebDavClient` so we are not depending on the change you've made. The change will still be good for others who do use `WebDavSession`.

**Comment by DecaTec** [comment]
OK, so I'll close this one.
Thanks for the input!
