### ISSUE TITLE
AdditionalProperties not working on Xamarin.Android (and possibly on Xamarin.iOS)

### ISSUE THREAD

**Issue by domenico-barbieri** [DecaTec/Portable-WebDAV-Library#51]
I noticed that additional properties don't work on Xamarin.Android. I was trying to get the additional property "favorite" from my server (a nextcloud installation). Investigating more I found that the helper function
GetUtf8EncodedXmlWebDavRequestString in WebDavHelper fails during serialization of Prop object when it contains any XmlElement in AdditionalProperties field, returning an empty string. This is the occurring exception:

`System.InvalidOperationException: There was an error generating the XML document. ---> System.InvalidOperationException: XmlAnyElementAttribute can only be applied to members of type XmlElement, XmlElement[] or XmlNode[]. The target object is System.Xml.Linq.XElement\n  at System.Xml.Serialization.XmlSerializationWriterInterpreter.WriteAnyElementContent (System.Xml.Serialization.XmlTypeMapMemberAnyElement member, System.Object memberValue) [0x0007c] in <69fb168feda3422cb50a9a4f302b574c>:0 \n  at System.Xml.Serialization.XmlSerializationWriterInterpreter.WriteElementMembers (System.Xml.Serialization.ClassMap map, System.Object ob, System.Boolean isValueList) [0x000c0] in <69fb168feda3422cb50a9a4f302b574c>:0 \n  at System.Xml.Serialization.XmlSerializationWriterInterpreter.WriteObjectElementElements (System.Xml.Serialization.XmlTypeMapping typeMap, System.Object ob) [0x0000c] in <69fb168feda3422cb50a9a4f302b574c>:0 \n  at System.Xml.Serialization.XmlSerializationWriterInterpreter.WriteObjectElement (System.Xml.
Serialization.XmlTypeMapping typeMap, System.Object ob, System.String element, System.String namesp) [0x00033] in <69fb168feda3422cb50a9a4f302b574c>:0 \n  at System.Xml.Serialization.XmlSerializationWriterInterpreter.WriteObject (System.Xml.Serialization.XmlTypeMapping typeMap, System.Object ob, System.String element, System.String namesp, System.Boolean isNullable, System.Boolean needType, System.Boolean writeWrappingElem) [0x001b9] in <69fb168feda3422cb50a9a4f302b574c>:0 \n  at System.Xml.Serialization.XmlSerializationWriterInterpreter.WriteMemberElement (System.Xml.Serialization.XmlTypeMapElementInfo elem, System.Object memberValue) [0x00212] in <69fb168feda3422cb50a9a4f302b574c>:0 \n  at System.Xml.Serialization.XmlSerializationWriterInterpreter.WriteElementMembers (System.Xml.Serialization.ClassMap map, System.Object ob, System.Boolean isValueList) [0x000ff] in <69fb168feda3422cb50a9a4f302b574c>:0 \n  at System.Xml.Serialization.XmlSerializationWriterInterpreter.WriteObjectElementElements (System.Xml.Seri
alization.XmlTypeMapping typeMap, System.Object ob) [0x0000c] in <69fb168feda3422cb50a9a4f302b574c>:0 \n  at System.Xml.Serialization.XmlSerializationWriterInterpreter.WriteObjectElement (System.Xml.Serialization.XmlTypeMapping typeMap, System.Object ob, System.String element, System.String namesp) [0x00033] in <69fb168feda3422cb50a9a4f302b574c>:0 \n  at System.Xml.Serialization.XmlSerializationWriterInterpreter.WriteObject (System.Xml.Serialization.XmlTypeMapping typeMap, System.Object ob, System.String element, System.String namesp, System.Boolean isNullable, System.Boolean needType, System.Boolean writeWrappingElem) [0x001b9] in <69fb168feda3422cb50a9a4f302b574c>:0 \n  at System.Xml.Serialization.XmlSerializationWriterInterpreter.WriteRoot (System.Object ob) [0x00059] in <69fb168feda3422cb50a9a4f302b574c>:0 \n  at System.Xml.Serialization.XmlSerializer.Serialize (System.Object o, System.Xml.Serialization.XmlSerializationWriter writer) [0x00016] in <69fb168feda3422cb50a9a4f302b574c>:0 \n  at System.Xml.Seria
lization.XmlSerializer.Serialize (System.Xml.XmlWriter xmlWriter, System.Object o, System.Xml.Serialization.XmlSerializerNamespaces namespaces) [0x00058] in <69fb168feda3422cb50a9a4f302b574c>:0 \n   --- End of inner exception stack trace ---\n  at System.Xml.Serialization.XmlSerializer.Serialize (System.Xml.XmlWriter xmlWriter, System.Object o, System.Xml.Serialization.XmlSerializerNamespaces namespaces) [0x00093] in <69fb168feda3422cb50a9a4f302b574c>:0 \n  at DecaTec.WebDav.Tools.WebDavHelper.GetUtf8EncodedXmlWebDavRequestString (System.Xml.Serialization.XmlSerializer xmlSerializer, System.Object objectToSerialize, System.Collections.Generic.KeyValuePair'2[System.String,System.String][] xmlNamespaces) [0x00073] in D:\\Sogeit\\Portable-WebDAV-Library\\DecaTec.WebDav\\Tools\\WebDavHelper.cs:59`

**Comment by DecaTec** [comment]
OK, I'll have a look at it.
Having so much problems when using Xamarin, it's maybe also a good idea to double the unit tests and add another unit test project for Xamarin.

**Comment by DecaTec** [comment]
After investigating, the core of the problem here is that an `XmlAnyElementAttribute` is being used for an array of `XElement`. I don't know why, but this is currently not supported on Xamarin.

I could "fix" it by switching from `XElement` to `XmlElement`, but these would be massive changes for the library. I even had to switch from .NET Standard 1.1 to 1.3.

So, I won't fix this at the moment, but I'll keep this issue in mind. From my pov, this had to be changed on Xamarin/Mono.

As a possible workaround for you: Use `WebDavClient` and provide the PropFind XML directly as `string`. I know that you loose the simplicity of just using `WebDavSession`, but for now, these's no other solution.

I also added info about this limitation in the wiki: https://github.com/DecaTec/Portable-WebDAV-Library/wiki/Xamarin
