### ISSUE TITLE
Assembly 'DecaTec.WebDav.XmlSerializers' not found

### ISSUE THREAD

**Issue by ghost** [DecaTec/Portable-WebDAV-Library#55]
I just tried this library. I created a new console project (C#, .NET 4.5.2). Then downloaded the DLL, tried installing via `Install-Package PortableWebDavLibrary -Version 1.1.3`, and also compiled the source directly. The result is always the same. When creating a new instance of `WebDavSession`: ``"System.IO.FileNotFoundException" in mscorlib.dll``:

> The assembly with display name 'DecaTec.WebDav.XmlSerializers' failed to load in the 'LoadFrom' binding context of the AppDomain with ID 1. The cause of the failure was: System.IO.FileNotFoundException: Could not load file or assembly 'DecaTec.WebDav.XmlSerializers, Version=1.1.3.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

Any ideas?

**Comment by DecaTec** [comment]
Cannot reproduce with a .NET 4.5.2 console application. Do you have any more info?
- What's the actual code your're using?
- Stacktrace?
- Visual Studio version?

**Comment by ghost** [comment]
That is how I did it:

- Open VS2015 (14.0.25431.01 Update 3)
- Create new project (C#, console, .NET 4.5.2)
- Add reference "DecaTec.WebDav.dll" (from https://github.com/DecaTec/Portable-WebDAV-Library/releases/download/v1.1.3.0/PortableWebDavLibrary_v1.1.3.0.zip)
- This is my code:

```
using DecaTec.WebDav;
using System;
using System.Net;
using System.Xml.Serialization;
namespace PortableDav2
{
    class Program
    {
        static void Main(string[] args)
        {
            var p = new Program();
            p.WebDav();
        }

        internal async void WebDav()
        {
            try
            {
                var serializer = new XmlSerializer(typeof(int));
                var credentials = new NetworkCredential("luke", "xxx");
                var webDavServerUrl = "https://owncloud/remote.php/dav/files/" + credentials.UserName + "/";
                var webDavSession = new WebDavSession(webDavServerUrl, credentials);
                var items = await webDavSession.ListAsync(@"dpsg/");
                foreach (var item in items)
                {
                    Console.WriteLine(item);
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
        }
    }
}

```

**Comment by ghost** [comment]
Never mind. I found the problem. The project was broken. I deleted folder `.vs`, now the problem is gone.
