### ISSUE TITLE
Problems with MoveAsync

### ISSUE THREAD

**Issue by milkin-vl** [DecaTec/Portable-WebDAV-Library#57]
Hello, dear developers. Thank for your great job!

I have problem with MoveAsync method if dest name has bracktes [ and ]

This problem arise periodically, but if arised - problem reproduced very stable.

In the same time (while problem reproduced) if i use other webdav clients for this operation - everthing ok.

MoveAsyn return false, without any exception and problem detalization.

I use Portable-WebDAV-Library version 1.1.2.

**Comment by milkin-vl** [comment]
I checked this problem with library version 1.1.4. Nothing changed.

**Comment by milkin-vl** [comment]
With Fiddler i found that library not escape url in result http request and spaces or brackets broken MoveAsync.

**Comment by DecaTec** [comment]
I can reproduce the problem.
Working on a solution.

**Comment by DecaTec** [comment]
Not only move is affected, but also copy.

Fixed with dbd77838f3f315e1852eb41c564c6370ca662226.
NuGet package 1.1.5 also released.

**Comment by milkin-vl** [comment]
Yes! Issue closed. Thanks for so fast solution! :)
