### ISSUE TITLE
System.FormatException: String was not recognized as a valid DateTime.

### ISSUE THREAD

**Issue by henningms** [DecaTec/Portable-WebDAV-Library#62]
Hi there,

Wanted to test the library with a CalDAV server, but I keep getting an exception when it's trying to parse the CreationDate property because it's null. This might be something that's weirdly set-up from the backend people, but would be nice if the library handled it.

**Comment by DecaTec** [comment]
Do you have a stack trace or some sort of code you're calling?

**Comment by DecaTec** [comment]
I'll close this as the issue may be resolved. If you have any more problems with this, feel free to reopen the issue.
