### ISSUE TITLE
WebDavSession.ListAsync: URL with converted special characters is converted back

### ISSUE THREAD

**Issue by jp-weber** [DecaTec/Portable-WebDAV-Library#66]
I have the problem, that a URL with special characters will be always transformed back (unescape), when I call the ListAsync function.

I debugged this problem and traced it back to the UriHelper.

https://github.com/DecaTec/Portable-WebDAV-Library/blob/ccc8e618dcc8e867722aea9a68a67aaa3069b6c3/DecaTec.WebDav/WebDavSession.cs#L900

https://github.com/DecaTec/Portable-WebDAV-Library/blob/ccc8e618dcc8e867722aea9a68a67aaa3069b6c3/DecaTec.WebDav/Tools/UriHelper.cs#L197

**Comment by DecaTec** [comment]
Do you have an example URL where you can reproduce the problem?
On which platform (Windows, Android,...) you are using the library?

**Comment by jp-weber** [comment]
Windows=> Win10 and WP8.1, but 🙈... I tested this yesterday only with folders without special characters on the lowest level... So sorry for the issue. The special characters make no problems. and I wonder why they were converted in the nextcloud app. Did Nextcloud/Owncloud have problems with special characters (<2015) and webdav?

The problem is the function that creates the parent folder:
https://github.com/nextcloud/windows-universal/blob/8c1bee4f43b710854c283aa328de6337a18a640e/NextcloudClient/NextcloudClient.cs#L544

**Comment by DecaTec** [comment]
I do know that Nextcloud doesn't accept some special characters. But this is a NC functionality/limitation, and has nothing to do with the WebDAV standard.
I also think that this depends on a possible enabled 4 byte support (see [here](https://docs.nextcloud.com/server/15/admin_manual/configuration_database/mysql_4byte_support.html)).
