### ISSUE TITLE
Async methods are missing CancellationToken

### ISSUE THREAD

**Issue by StefH** [DecaTec/Portable-WebDAV-Library#8]
It would be very useful to have also a method with **requestUrl / requestUri** and **cancellationToken**. (With no Lock parameter)

Like:
`public Task<WebDavResponseMessage> MkcolAsync(string requestUrl, CancellationToken cancellationToken);`

and

`public Task<WebDavResponseMessage> MkcolAsync(Uri requestUri, CancellationToken cancellationToken);`

**Comment by DecaTec** [comment]
As a workaround you can simply pass `null` for these operations for not using a lock token.

**Comment by StefH** [comment]
Sounds like a good work-around; however if you have time to fix this, that would be great.

**Comment by DecaTec** [comment]
Resolved with https://github.com/DecaTec/Portable-WebDAV-Library/commit/60b4ecd062acd1b360804bfc68803ba60dcef255
