### ISSUE TITLE
DecaTec.WebDav.Uwp.UnitTest_TemporaryKey.pfx is missing on github

### ISSUE THREAD

**Issue by StefH** [DecaTec/Portable-WebDAV-Library#9]
The file DecaTec.WebDav.Uwp.UnitTest_TemporaryKey.pfx which is referred in the uwp unit-test is missing.

**Comment by DecaTec** [comment]
Imho the file is not needed for successful unit tests. I think I can remove it fro the project.

**Comment by DecaTec** [comment]
Removed the files (see Commit 2ac10a363fbed2abbc28730b1409f4f9716e4075)
